apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    system: learn-kubernetes
    env: test
    section: '5'
    target: pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
